// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/rescript-jest/src/jest.bs.js";
import * as Uuid from "uuid";

Jest.describe("UUID", (function (param) {
        return Jest.test("v4", (function (param) {
                      var uuid = Uuid.v4();
                      return Jest.Expect.toEqual(Jest.Expect.expect(uuid.length), 36);
                    }));
      }));

export {
  
}
/*  Not a pure module */
